In [1]:
import numpy as np

In [2]:
grade = np.array([85,90,88,92,95,80,75,98,89,83])

In [3]:
grade

array([85, 90, 88, 92, 95, 80, 75, 98, 89, 83])

In [4]:
# To calculate mean 
mean_grade=np.mean(grade)

In [5]:
mean_grade

87.5

In [6]:
# to calculate median

median_grade=np.median(grade)
median_grade

88.5

In [7]:
# to calculate standard deviation

std_grade =np.std(grade)
std_grade

6.591661399070799

In [8]:
# Use numpy function to find the maximum and minimum of the grades.

max_grade = np.max(grade)
max_grade

98

In [9]:
min_grade = np.min(grade)
min_grade

75

In [10]:
print(f'your minimum grade is {min_grade}')

your minimum grade is 75


In [11]:
# Use numpy function to sort the grades in ascending order

sorted_grades = np.sort(grade)
sorted_grades

array([75, 80, 83, 85, 88, 89, 90, 92, 95, 98])

In [12]:
# Use numpy function to find the index of the highest grade in the array.
highest_index = np.argmax(grade)
highest_index

7

In [14]:
# Use numpy function to count the number of students who scored above 90.

count_above_90 = np.sum(np.array(grade) > 90)
count_above_90

3

In [17]:
# Use numpy function to calculate the percentage of students who scored above 90.

above_90 = (np.sum(np.array(grade) > 90) / np.array(grade).size) * 100
above_90

30.0

In [19]:
# Use numpy function to calculate the percentage of students who scored below 75.

below_75 = (np.sum(np.array(grade) < 75) / np.array(grade).size) * 100
below_75

0.0

In [21]:
# Use numpy function to extract all the grades above 90 and put them in a new array called "high_performers".
grades_array = np.array(grade)
high_performers = grades_array[grades_array > 90]
high_performers

array([92, 95, 98])

In [22]:
# Create a new array called "passing_grades" that contains all the grades above 75.

passing_grades = grades_array[grades_array > 75]
passing_grades

array([85, 90, 88, 92, 95, 80, 98, 89, 83])